import { Link, useLocation } from "@tanstack/react-router";
import { Bell, ChevronDown, FileCheck2, FileSearch, History, LayoutDashboard, Menu, ShieldCheck, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";

const navItems = [
  { label: "Overview", to: "/", icon: LayoutDashboard }, { label: "Screen document", to: "/screening", icon: FileSearch }, { label: "Analysis results", to: "/analysis", icon: FileCheck2 }, { label: "Verification history", to: "/history", icon: History },
];
export function VeriDocShell({ children }: { children: ReactNode }) {
  const location = useLocation(); const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="min-h-screen bg-background text-foreground"><aside className={`fixed inset-y-0 left-0 z-50 flex w-[250px] flex-col bg-sidebar text-sidebar-foreground transition-transform duration-200 lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
    <div className="flex h-[86px] items-center gap-3 border-b border-sidebar-border px-6"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground shadow-lg shadow-sidebar-primary/15"><ShieldCheck size={23} /></div><div><div className="text-[15px] font-semibold tracking-tight">VeriDoc <span className="text-sidebar-primary">AI</span></div><div className="mt-0.5 text-[10px] uppercase tracking-[0.18em] text-sidebar-foreground/55">Identity screening</div></div><Button variant="ghost" size="icon" className="ml-auto text-sidebar-foreground hover:bg-sidebar-accent lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={18} /></Button></div>
    <div className="px-4 pt-7"><div className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-sidebar-foreground/40">Workspace</div><nav className="space-y-1" aria-label="Main navigation">{navItems.map((item) => { const Icon = item.icon; const active = location.pathname === item.to || (item.to !== "/" && location.pathname.startsWith(item.to)); return <Link key={item.to} to={item.to} onClick={() => setMobileOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-[13px] font-medium transition-colors ${active ? "bg-sidebar-accent text-sidebar-primary" : "text-sidebar-foreground/65 hover:bg-sidebar-accent/70 hover:text-sidebar-foreground"}`}><Icon size={17} /><span>{item.label}</span>{active && <span className="ml-auto status-dot bg-sidebar-primary" />}</Link>; })}</nav></div>
    <div className="mt-auto p-4"><div className="rounded-lg border border-sidebar-border bg-sidebar-accent/45 p-3"><div className="flex items-center gap-2 text-[11px] font-semibold text-sidebar-foreground"><span className="status-dot bg-sidebar-primary" />Demo environment</div><p className="mt-2 text-[11px] leading-relaxed text-sidebar-foreground/52">Fictional records are active for this presentation.</p></div><div className="mt-5 flex items-center gap-3 border-t border-sidebar-border pt-4"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-sidebar-primary/15 text-xs font-semibold text-sidebar-primary">AS</div><div className="min-w-0"><div className="truncate text-xs font-medium">Ananya Sharma</div><div className="truncate text-[10px] text-sidebar-foreground/45">Senior reviewer</div></div><ChevronDown size={14} className="ml-auto text-sidebar-foreground/35" /></div></div>
  </aside>{mobileOpen && <button aria-label="Close navigation overlay" className="fixed inset-0 z-40 bg-navy/40 lg:hidden" onClick={() => setMobileOpen(false)} />}
  <div className="lg:pl-[250px]"><header className="sticky top-0 z-30 flex h-[70px] items-center justify-between border-b border-border/80 bg-background/90 px-5 backdrop-blur-md sm:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="-ml-2 lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={19} /></Button><div className="hidden text-xs text-muted-foreground sm:block">Workspace <span className="mx-2 text-border">/</span> <span className="text-foreground">{location.pathname === "/" ? "Overview" : location.pathname.slice(1).replaceAll("-", " ")}</span></div><div className="sm:hidden text-sm font-semibold">VeriDoc <span className="text-cyan">AI</span></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-full border border-warning/25 bg-warning/10 px-3 py-1.5 text-[11px] font-medium text-warning-foreground md:flex"><span className="status-dot bg-warning" />Demo mode</div><Button variant="ghost" size="icon" aria-label="Notifications"><Bell size={18} /></Button><div className="hidden h-5 w-px bg-border sm:block" /><div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-[11px] font-semibold text-primary-foreground">AS</div><span className="hidden text-xs font-medium sm:block">Ananya Sharma</span></div></div></header><main>{children}</main></div></div>;
}
export function PageIntro({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-2 text-[10px] font-bold uppercase tracking-[0.18em] text-cyan">{eyebrow}</div><h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-[28px]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{description}</p></div>{action && <div className="shrink-0">{action}</div>}</div>; }
export function Surface({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-lg border border-border bg-card shadow-[0_8px_30px_color-mix(in_oklch,var(--navy)_5%,transparent)] ${className}`}>{children}</section>; }
export function StatusPill({ value }: { value: string }) { const tone = value === "Likely genuine" || value === "Passed" || value === "Complete" ? "success" : value === "Suspicious" || value === "Failed" ? "danger" : "warning"; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-semibold ${tone === "success" ? "border-success/25 bg-success/10 text-success-foreground" : tone === "danger" ? "border-danger/25 bg-danger/10 text-danger-foreground" : "border-warning/30 bg-warning/10 text-warning-foreground"}`}><span className={`status-dot ${tone === "success" ? "bg-success" : tone === "danger" ? "bg-danger" : "bg-warning"}`} />{value}</span>; }
